apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: ldapadmin
  name: phpldapadmin-service
spec:
  ports:
    - port: 80
  selector:
    app: phpldapadmin
